--- #YAML:1.0
name:               Finance-Currency-Convert-Custom
version:            1.0
abstract:           Finance::Currency::Convert + own fetch rates
author:
    - Dmitry Nikolayev <dmitry@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Finance::Currency::Convert:              0
    LWP::UserAgent:			     0
resources:    
    repository:   http://perl-finance-currency-convert-custom.googlecode.com/svn/trunk/
no_index:
    directory:
        - t
generated_by:       ExtUtils::MakeMaker version 6.4801
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4